#!/usr/bin/env bash

# Variaveis

icn1=""
 icn2=""
  icn3=""
   icn4=""
  icn5=""
 icn6="   "
icn7=""
 line1="\033[1;31m┌───────────────────┐\033[m"
  line2="\033[1;31m│\033[m"
   line3="\033[1;36m│      ┌─────────┐\033[m \033[1;31m │\033[m"
 #line5="\033[36m       └─────────┘ \033[m "
 line6="\033[31m└──────│\033[m`uname --kernel-name`"
line7="\033[32m└──────│\033[mVersão:`uname --kernel-release | sed 's/-.*//g'`"
 line8="\033[31m└──────│\033[m`uname -a | awk '{print $2}'`"
  line9="\033[31m└──────│\033[mTotal: `free -h | sed -n 2p | awk '{print $2}'`"
   line10="\033[36m└───────────────────┘\033[m"
  line11="\033[32m└──────│\033[mUsada: `free -h | sed -n 2p | awk '{print $3}'`"
 line12="\033[34m└──────│\033[mLivre: `free -h | sed -n 2p | awk '{print $4}'`"
line13="\033[31m└──────│\033[mTotal: `df -h | sed -n 4p | awk '{print $2}'`"
 line14="\033[32m└──────│\033[mUsado:  `df -h | sed -n 4p | awk '{print $3}'`"
  line15="\033[33m└──────│\033[mDispo:  `df -h | sed -n 4p | awk '{print $4}'`"
   line16="\033[34m└──────│\033[mUso:    `df -h | sed -n 4p | awk '{print $5}'`"
  line16="\033[34m└──────│\033[mUso:    `df -h | sed -n 4p | awk '{print $5}'`"
 line17="\033[31m└──────│\033[mMod: `cat /proc/cpuinfo | sed -n 5p | awk '{print $4}'| sed 's/(.*//g'`"
line18="\033[32m└──────│\033[m`cat /proc/cpuinfo | sed -n 5p | awk '{print $5}'`"
 line19="\033[33m└──────│\033[m`cat /proc/cpuinfo | sed -n 5p | awk '{print $9}'`"
  line20="\033[31m└────│\033[mHora: `date | awk '{print $4}'`"
   line21="\033[32m└────│\033[mData: `date +%d/%m/%y`"
  line22="\033[31m└────│\033[mUsuario: `echo "$USER"`"
 clear

# Display

     echo -e "$line1  $line1"
    echo -e "$line2 K E R N E L     $icn1 $line2  $line2 T E M P O    $icn6$line2"
   echo -e "$line10  $line10"
  echo -e "$line6          $line20"
echo -e "$line7   $line21"
     echo -e "$line1  $line1"
    echo -e "$line2 D I S T R O     $icn2 $line2  $line2 U S U A R I O   $icn7 $line2"
   echo -e "$line10  $line10"
  echo -e "$line8      $line22"
 echo -e "$line1  $line1"
echo -e "$line2 M E M O R I A   $icn3 $line2  $line2 C P U           $icn5 $line2"
    echo -e "$line10  $line10"
   echo -e "$line9   $line17"
  echo -e "$line11   $line18"
 echo -e "$line12   $line19"
echo -e "$line1"
    echo -e "$line2 D I S C O       $icn4 $line2"
   echo -e "$line10"
  echo -e "$line13"
 echo -e "$line14"
echo -e "$line15"
    echo -e "$line16"

# Troque o icone da variavel (icn2) pelo icone de sua distribuição.

#                                           




